backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "cakes"
    label: "Cakes"
    folder: "content/cakes"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Flavor", name: "flavor", widget: "select", options: ["Traditional", "Strawberry", "Chocolate Fudge", "Ferrero Rocher"] }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
